# Generated by Django 4.2.7 on 2025-11-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('system', 'System')], max_length=10),
        ),
    ]
