# Generated by Django 4.2.7 on 2025-12-24 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_sender_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomatedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for this automated response', max_length=200)),
                ('trigger_type', models.CharField(choices=[('keyword', 'Keyword Match'), ('greeting', 'Greeting Message'), ('first_message', 'First Message (Welcome)'), ('offline', 'All Admins Offline'), ('business_hours', 'Outside Business Hours')], max_length=20)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords to match (for keyword trigger type)')),
                ('response_message', models.TextField(help_text='The automated message to send')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority responses are checked first')),
                ('delay_seconds', models.IntegerField(default=0, help_text='Delay in seconds before sending the automated response (0 for immediate)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Automated Response',
                'verbose_name_plural': 'Automated Responses',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_message_content', models.TextField(help_text='The customer message that triggered this response')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('automated_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.automatedresponse')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_responses', to='chat.chatsession')),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automated_response_log', to='chat.message')),
            ],
            options={
                'verbose_name': 'Automated Response Log',
                'verbose_name_plural': 'Automated Response Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
